### PR TITLE
Improvements `ssd_write`/`ssd_read` and conversion `Simulation` <-> `NamedTuple`

### PR DESCRIPTION
**Pull request by fhagemann**
Related to #68 and #107.
(To be honest, I'm not exactly sure what #68 is addressing, so it might even be fixed with this PR.)

I added tests to `runtests.jl` for the conversion from `Simulation` to `NamedTuple` and back (2cf6e0b).

This conversion failed when parts of the simulation were `missing`, 
e.g. the `electric_field`, `electron_drift_field`, `hole_drift_field` or any of the `weighting_potentials`.

To fix this:
- the conversion from `Simulation` to `NamedTuple` and back was updated (bfc0aa5).
  This update still allows to "understand" HDF5 files with `Simulations` converted `NamedTuples` since v0.6 and does not come with breaking changes.
- the conversion from `Missing` to `NamedTuple` was updated (1b85a4e) such that it is stored as `String` now. 
  If `Missing` is converted to a `NamedTuple` with value `missing`, [LegendHDF5IO.jl](https://github.com/legend-exp/LegendHDF5IO.jl) will not be able to write it to a HDF5 file. This results in `ssd_write(filename, sim)` failing with an `ArgumentError: Value to write, of type Missing,is not a table`.
- the operator `==` was overridden for most of the structs (0cff6d2) to compare simulations before and after read-in.
  This is used in the tests.

In addition, the methods `ssd_write` and `ssd_read` are now exported (7c65895), have docstrings (f09e71b), and are somewhat explained in the manual (4717677).

### CODE REVIEW

**Comment by fhagemann** [comment]
The latest commit (props to @lmh91 for finding out what the problem was) prevents the tests from crashing.
It comes from `Int` overflows on 32bit machines, when big values in the config files are defined as integers.

This could be prevented by adding a `float` statement to [`_parse_value`](https://github.com/fhagemann/SolidStateDetectors.jl/blob/IO/src/ConstructiveSolidGeometry/IO.jl#L60), i.e. changing
```julia
@inline _parse_value(::Type{T}, x::Real, unit::Unitful.Units) where {T} = T(to_internal_units(x * unit))
```
to
```julia
@inline _parse_value(::Type{T}, x::Real, unit::Unitful.Units) where {T} = T(to_internal_units(float(x) * unit))
```

I am not sure whether this might cause rounding error issues. I believe not (`Floats` will be parsed as they were, only `Ints` will be converted to `Floats`), but better be safe than sorry and ask. `T` is always a `Float` anyhow...

**Comment by fhagemann** [comment]
Also, is #68 fixed with this PR?

**Comment by lmh91** [comment]
> Also, is #68 fixed with this PR?

#68 is very general, but I would close it with this PR.

**Comment by lmh91** [comment]
> The latest commit (props to @lmh91 for finding out what the problem was) prevents the tests from crashing.
> It comes from `Int` overflows on 32bit machines, when big values in the config files are defined as integers.
> 
> This could be prevented by adding a `float` statement to [`_parse_value`](https://github.com/fhagemann/SolidStateDetectors.jl/blob/IO/src/ConstructiveSolidGeometry/IO.jl#L60), i.e. changing
> 
> ```julia
> @inline _parse_value(::Type{T}, x::Real, unit::Unitful.Units) where {T} = T(to_internal_units(x * unit))
> ```
> 
> to
> 
> ```julia
> @inline _parse_value(::Type{T}, x::Real, unit::Unitful.Units) where {T} = T(to_internal_units(float(x) * unit))
> ```
> 
> I am not sure whether this might cause rounding error issues. I believe not (`Floats` will be parsed as they were, only `Ints` will be converted to `Floats`), but better be safe than sorry and ask. `T` is always a `Float` anyhow...

Isn't the problem how the `x` is interpreted in the first place?

I think we had this before and i caused numerical issues sometimes. But I am not sure. Also, with the new way we initialize the grid those issues should not matter anymore.

**Comment by fhagemann** [comment]
Regarding my latest commit (4cae7a5):

If the configuration file parser interprets `x` as `Float`, `float(x)` will not do anything.
However, when `x` is an `Int`, the conversion to `float` should not result in any rounding errors.

Only difference is, that the unit conversion for lengths returns a `Rational`, if `x` is an `Int`:
```julia
julia> uconvert(u"m", 25u"mm")
1//40 m

julia> uconvert(u"m", 25.0u"mm")
0.025 m
```

Evaluating the units might not be any problem for `lengths` (where we only multiply powers of 10), and the conversion from `Int` to `Float` will be trivial. For conversion of angles (`deg` <-> `rad`), we have to convert `x` to a `Float` anyhow.

**Review by lmh91 — APPROVED** [review]
Thanks :)

**Pull request merged**
