### PR TITLE
Surfaceprimitives

### PR DESCRIPTION
**Pull request by hervasa2**
I have added the distance_to_surface function for all the conal surfaces (ConeMantle, CylindricalAnnulus, ConalPlane) and made small corrections to their dependency in SurfacePrimitives/Plane.jl. An example follows
`cone = CSG.Cone(0, 1, 1, 3, π/6, 3π/2, -3, 3)`
`plot(cone, SSD_style = :surface, color = color, camera = (30,30))`
`plot!(cone, SSD_style = :wireframe, color = :black)`
distance_to_cone
We can scan the cone along z to explore the distance to surface of the cone for each point in the world
`D[i,j] = CSG.distance_to_surface(CSG.CylindricalPoint{T}(r,φ,z),cone)`
`heatmap(Φ,R,D, c = cgrad(:inferno, scale =:exp), clims = (0,3), projection = :polar, title = string("z = ",z))`
zcuts
Lest take a closer look at z = 2. I have also used the `in` function as a further check
`point = CSG.CylindricalPoint{T}(r,φ,2)`
 `D[i,j] = point in a ? CSG.distance_to_surface(point,cone) : NaN`
`heatmap(Φ,R,D, c = cgrad(:inferno, scale =:exp), projection = :polar, title = "z = 2")`
z2cut
We can also scan the cone along φ 
`D[j,i] = CSG.distance_to_surface(CSG.CylindricalPoint{T}(r,φ*π/180,z),cone) `
`heatmap(R,Z,D, c = cgrad(:inferno, scale =:exp), clims = (0,3), title = string("φ = ", φ, "°"), aspect_ratio = 1)`
phicuts
Lest take a closer look at φ = 90°
`point = CSG.CylindricalPoint{T}(r,π/2,z)`
`D[j,i] = point in a ? CSG.distance_to_surface(point,cone) : NaN`
`heatmap(R,Z,D, c = cgrad(:inferno, scale =:exp), title = string("φ = 90°"), aspect_ratio = 1)`
phi90cut

### CODE REVIEW

**Comment by hervasa2** [comment]
Added the distance_to_surface function for all the toroidal surfaces (TorusMantle, TorroidalAnnulus)
`torus = CSG.Torus(4,0,3,π/6,π/2,0,π/2)`
`plot(torus, SSD_style = :surface, c = color, camera = (30,30))`
Screen Shot 2021-02-18 at 12 00 06 AM
Scanning the torus along φ
`D[j,i] = CSG.distance_to_surface(CSG.CylindricalPoint{T}(r,φ*π/180,z),torus) `
`heatmap(R,Z,D, c = cgrad(:inferno, scale =:exp), clims = (0,3), title = string("φ = ", φ, "°"), aspect_ratio = 1)`
phicuts_torus

**Comment by hervasa2** [comment]
Scanning the torus along z
` D[i,j] = CSG.distance_to_surface(CSG.CylindricalPoint{T}(r,φ,z),torus)`
` heatmap(Φ,R,D, c = cgrad(:inferno, scale =:exp), clims = (0,3), projection = :polar, title = string("z = ",z))`
zcuts_torus

**Comment by hervasa2** [comment]
Here is a couple more examples because why not they are cool
`torus = CSG.Torus(4,1,3,π/6,3π/2,0,7π/4)`
Screen Shot 2021-02-18 at 12 36 40 AM
phicuts_torus2
zcuts_torus2

**Comment by lmh91** [comment]
The `refactorCSG` branch moved to `v0.6` branch. I will close this PR and delete the branch.

**Pull request closed without merging**
