### PR TITLE
Clean up for v0.6.0 release

### PR DESCRIPTION
**Pull request by fhagemann**
This PR does some cleanup for the v0.6.0 release.
- Obsolete functions were removed (#87)
- Docs were added (props to @lmh91) for `Grid`
- Docstrings were added for exported functions
- Example config files were updated (f2d6b78) to avoid deprecation warnings
- Update `get_world_limits_from_objects` (de97af5)
- Functions from IntervalSets.jl: `endpoints` and `width` replaced self-written ones ( c942aa8, 22ec004, 80ce13e)
- `LengthQuantity` and `AngleQuantity` were moved from `SolidStateDetectors` to `ConstructiveSolidGeometry` (e2fc079)
- `to_internal_units` was changed (b24d6ed) to only expect one argument (and determine the internal unit from the argument)
- Checks were added to ensure that all `input_units` match what they are describing (984e8ad)
- Keywords to disable painting were added (ead7bd8)

### CODE REVIEW

**Comment by fhagemann** [comment]
## Clean-up

Functions that are never called elsewhere:

- [`merge_axis_ticks_with_important_ticks`](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/cleanup/src/Axes/DiscreteAxis.jl#L67)
- [`_common_length`](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/cleanup/src/ChargeDrift/ChargeDrift.jl#L13)
- [`_drift_charge`](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/cleanup/src/ChargeDrift/ChargeDrift.jl#L60)
- [`add_baseline_and_extend_tail`](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/cleanup/src/Event/Event.jl#L108)
- [`add_points_and_interpolate`](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/cleanup/src/Grids/RefineGrid.jl#L160) and all other functions in [RefineGrid.jl](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/cleanup/src/Grids/RefineGrid.jl)
- [`get_interpolated_drift_field(ef::ElectricField)`](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/cleanup/src/Simulation/Simulation.jl#L939)
- `searchsortednearest` seems to be defined twice:
  - in [Grids.jl](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/cleanup/src/Grids/Grids.jl#L71) (where it is `searchsortednearest(::Point, ::Grid)`)
  - in [DetectorGeometries.jl](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/cleanup/src/SolidStateDetector/DetectorGeometries.jl#L178) (where it is `searchsortednearest(::Grid, ::Point)`)
- [`find_closest_gridpoint`](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/cleanup/src/SolidStateDetector/Object.jl#L13)
- [`generate_random_startpositions`](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/cleanup/src/SolidStateDetector/SolidStateDetector.jl#L146)
- [`is_depleted`](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/cleanup/src/Types/point_types.jl#L61)


File restructuring and moving code:

- Should we split Simulation.jl into smaller chunks (for example capacitance calculations could go into a separate file)
- Can some of DetectorGeometries.jl and SigGenInterface.jl go to the folder `IO`?

**Comment by lmh91** [comment]
IMO:

Can be removed:
- `merge_axis_ticks_with_important_ticks`
- `_drift_charge`
- `add_points_and_interpolate`
- `generate_random_startpositions`

Optional removed:
- You can remove `_common_length` and inline its code if you want as it just used once. 
- `find_closest_gridpoint`


Functionalities I would keep: 
- `add_baseline_and_extend_tail`
- `is_depleted` 
- `get_interpolated_drift_field(ef::ElectricField)` is used at several places in the code. (Though this might be changed anyhow in near future v0.7)?

Modify:
- `searchsortednearest` -> just use (::Grid, ::point) to be consistent with e.g. `searchsortedfirst(::Array, ::Real)`


Yes, we can split the `Simulation.jl` file.

Yes, IO related code should go to IO.

**Comment by fhagemann** [comment]
> Optional removed:
> 
>     * You can remove `_common_length` and inline its code if you want as it just used once.
> 

`_common_length` is only called by itself

**Comment by lmh91** [comment]
Than delete it.

**Comment by fhagemann** [comment]
>     * `get_interpolated_drift_field(ef::ElectricField)` is used at several places in the code. (Though this might be changed anyhow in near future v0.7)?

There are other methods, also called `get_interpolated_drift_field`, but none using only `ElectricField` as argument

**Comment by lmh91** [comment]
> > ```
> > * `get_interpolated_drift_field(ef::ElectricField)` is used at several places in the code. (Though this might be changed anyhow in near future v0.7)?
> > ```
> 
> There are other methods, also called `get_interpolated_drift_field`, but none using only `ElectricField` as argument

What about 
```
    e_drift_field = get_interpolated_drift_field(s.electron_drift_field);
    h_drift_field = get_interpolated_drift_field(s.hole_drift_field);
```
in `simulate_waveforms`? These are of type `ElectricField`.

**Comment by fhagemann** [comment]
> What about
> 
> ```
>     e_drift_field = get_interpolated_drift_field(s.electron_drift_field);
>     h_drift_field = get_interpolated_drift_field(s.hole_drift_field);
> ```
> 
> in `simulate_waveforms`? These are of type `ElectricField`.

Ah, right. I thought, they were separate types.. Then, I'll leave it ;)

**Comment by lmh91** [comment]
> > What about
> > ```
> >     e_drift_field = get_interpolated_drift_field(s.electron_drift_field);
> >     h_drift_field = get_interpolated_drift_field(s.hole_drift_field);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in `simulate_waveforms`? These are of type `ElectricField`.
> 
> Ah, right. I thought, they were separate types.. Then, I'll leave it ;)

We might want to change this to `VectorField` (and also `ScalarField` for `ElectricPotential`, ...).
But not right now.

**Comment by fhagemann** [comment]
I would leave this PR as is and suggest one final PR before the v0.6.0 release in which we take care of code style, e.g.:
- find consistent naming for variables (detectors are `c`, `d`, `ssd`, `det`), simulation (`s`, `sim`, `simulation`)
- consistent naming of types (to only use `CylindricalGrid{T}}` or `Grid{T,3,Cylindrical}}` in functions, etc.)
-  write one-liner in one line etc.
- consistent docstrings

**Comment by lmh91** [comment]
Sounds good.

**Pull request merged**
