### PR TITLE
Added LEGEND ICPC and MJD PCC detector geometries to examples

### PR DESCRIPTION
**Pull request by hervasa2**

### CODE REVIEW

**Comment by giordano** [comment]
# [Codecov](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26?src=pr&el=h1) Report
> Merging [#26](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26?src=pr&el=desc) into [master](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/commit/63ca84a166f759fb73be098ea0592acde1780db3&el=desc) will **decrease** coverage by `9.82%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master      #26      +/-   ##
==========================================
- Coverage   47.78%   37.96%   -9.83%     
==========================================
  Files          71       70       -1     
  Lines        5077     4157     -920     
==========================================
- Hits         2426     1578     -848     
+ Misses       2651     2579      -72     
```


| [Impacted Files](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/ChargeDriftModels/Vacuum/Vacuum.jl](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26/diff?src=pr&el=tree#diff-c3JjL0NoYXJnZURyaWZ0TW9kZWxzL1ZhY3V1bS9WYWN1dW0uamw=) | `33.33% <0.00%> (-33.34%)` | :arrow_down: |
| [src/Geometries/Vectors.jl](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26/diff?src=pr&el=tree#diff-c3JjL0dlb21ldHJpZXMvVmVjdG9ycy5qbA==) | `11.11% <0.00%> (-22.23%)` | :arrow_down: |
| [src/PotentialSimulation/RedBlack/RedBlack.jl](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26/diff?src=pr&el=tree#diff-c3JjL1BvdGVudGlhbFNpbXVsYXRpb24vUmVkQmxhY2svUmVkQmxhY2suamw=) | `47.36% <0.00%> (-20.03%)` | :arrow_down: |
| [src/SolidStateDetectors.jl](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26/diff?src=pr&el=tree#diff-c3JjL1NvbGlkU3RhdGVEZXRlY3RvcnMuamw=) | `33.33% <0.00%> (-16.67%)` | :arrow_down: |
| [src/PotentialSimulation/WeightingPotential.jl](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26/diff?src=pr&el=tree#diff-c3JjL1BvdGVudGlhbFNpbXVsYXRpb24vV2VpZ2h0aW5nUG90ZW50aWFsLmps) | `17.46% <0.00%> (-14.57%)` | :arrow_down: |
| [src/Axes/DiscreteAxis.jl](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26/diff?src=pr&el=tree#diff-c3JjL0F4ZXMvRGlzY3JldGVBeGlzLmps) | `31.32% <0.00%> (-10.56%)` | :arrow_down: |
| [src/ElectricField/ElectricField.jl](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26/diff?src=pr&el=tree#diff-c3JjL0VsZWN0cmljRmllbGQvRWxlY3RyaWNGaWVsZC5qbA==) | `69.23% <0.00%> (-9.72%)` | :arrow_down: |
| [src/ChargeDrift/ChargeDriftCylindrical.jl](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26/diff?src=pr&el=tree#diff-c3JjL0NoYXJnZURyaWZ0L0NoYXJnZURyaWZ0Q3lsaW5kcmljYWwuamw=) | `58.53% <0.00%> (-9.21%)` | :arrow_down: |
| [src/Grids/Grids.jl](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26/diff?src=pr&el=tree#diff-c3JjL0dyaWRzL0dyaWRzLmps) | `22.98% <0.00%> (-8.05%)` | :arrow_down: |
| [src/ChargeDrift/ChargeDrift.jl](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26/diff?src=pr&el=tree#diff-c3JjL0NoYXJnZURyaWZ0L0NoYXJnZURyaWZ0Lmps) | `80.00% <0.00%> (-5.00%)` | :arrow_down: |
| ... and [29 more](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26?src=pr&el=footer). Last update [63ca84a...c28f486](https://codecov.io/gh/JuliaPhysics/SolidStateDetectors.jl/pull/26?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by giordano** [comment]
I have no idea why there is a code coverage report with my account

**Comment by aminya** [comment]
> 
> 
> I have no idea why there is a code coverage report with my account

You're becoming a robot. 🤖

**Comment by oschulz** [comment]
> I have no idea why there is a code coverage report with my account

Me neither, lol. :-)

**Comment by oschulz** [comment]
@hervasa2, I'd prefer to not name these detectors LEGEND and MJD - they're not special designs, right? May be better to name them after the actual commercial model.

Also - I assume there's not confidential information in these designs, we have an Ok from the manufacturer to make this public?

**Comment by hervasa2** [comment]
@oschulz That is a really good point! I am pretty sure these are not confidential since we have shown the designs in talks. However, it is worth double checking. I will ask around. I'll also rename them as you suggested since they are not specific to LEGEND or MJD.

**Pull request closed without merging**
