### PR TITLE
Improve depletion handling: Bulk type is determined through charge density

### PR DESCRIPTION
**Pull request by lmh91**
This addresses #95. 

The bulk type is determined for each grid point based on its local charge density. 
This enables simulation of both, p+ and n+ layers at the same time. 

Here a small example of an 3D simulation of an PN-Junction with a overdoped n+ and p+ layer on both ends.

```julia
using SolidStateDetectors
using Plots
using SpecialFunctions

struct CustomChargeDensity{T} <: SolidStateDetectors.AbstractChargeDensity{T}
    A::T
    S::T
    PN::T
    NP::T # N+
    PP::T # P+
end
function SolidStateDetectors.get_charge_density(cdm::CustomChargeDensity{T}, pt::CartesianPoint{T}) where {T}
    # just a dummy model for a pn-junction with overdoped n+ and p+ layer on both ends
    cdm.A * erf(cdm.S * (pt[1] - cdm.PN)) + 
    2 * cdm.A * erf(10 * cdm.S * (pt[1] - cdm.NP)) + 
    2 * cdm.A * erf(10 * cdm.S * (pt[1] - cdm.PP))
end 
function SolidStateDetectors.get_charge_density(cdm::CustomChargeDensity{T}, pt::CylindricalPoint{T}) where {T}
    SolidStateDetectors.get_charge_density(cdm, CartesianPoint(pt))
end

begin
    T = Float32
    sim = Simulation{T}(SSD_examples[:InfiniteParallelPlateCapacitor])
    
    ccdm = CustomChargeDensity{Float32}( 1*10^17, -10^4, 0, 0.00035, -0.00035 ) # meter not mm
    sim.detector.semiconductors[1].charge_density_model = ccdm
    
    xs = -5e-4:1e-6:5e-4
    charge_vec = similar(xs)
    for ix in eachindex(xs)
        pt = CartesianPoint{T}(xs[ix], 0, 0)
        charge_vec[ix] = pt in sim.detector.semiconductors[1] ? 
            SolidStateDetectors.get_charge_density(sim.detector.semiconductors[1], pt) :
            0 
    end
    
    calculate_electric_potential!(sim, 
        max_refinements = 4, 
        init_grid_spacing = T.( (1e-4, 1e-3, 1e-3) ), 
        convergence_limit = 1e-3,
        depletion_handling=true
    )
    
    plot(
        plot(xs, charge_vec, ylabel = "impurity density [1/m^3]", xlabel = "x [m]"),
        plot(sim.ρ, aspect_ratio = :none, y = 0),
        plot(sim.electric_potential, aspect_ratio = :none, y = 0),
        plot(sim.point_types, aspect_ratio = :none, y = 0),
        layout = (4,1), size = (800, 1200)
    )
end    
```
pn_junction_sim

### CODE REVIEW

**Comment by rjtayl** [comment]
@lmh91, if there are two overlapping geometries with different charge densities, then how is the charge density in the overlapping region handled?

**Comment by lmh91** [comment]
The package assumes that there are no (physical) overlapping geometries. 
Overlapping contacts with the semiconductor are fine as the potential is than fixed and the charge basically does not matter at the corresponding points (volume) in the relaxation. 

Are you talking about two (or more) semiconductors in one simulation?

**Comment by rjtayl** [comment]
Thanks, that makes sense. 

I was wondering if we could build a single semiconductor with complicated charge distribution by overlapping semiconductor geometries, but it sounds like that isn't possible.

**Comment by fhagemann** [comment]
If, for example, you want to "overlap" two geometries, you could define these volumes in the `CustomChargeDensity` struct:
```julia
struct CustomChargeDensity{T, N} <: SolidStateDetectors.AbstractChargeDensity{T}
    G1::SolidStateDetectors.AbstractGeometry{T, N}
    G2::SolidStateDetectors.AbstractGeometry{T, N}
    #... other parameters needed for calculations, you can also include other `ChargeDensity` objects here
end

function SolidStateDetectors.get_charge_density(cdm::CustomChargeDensity{T}, pt::SolidStateDetectors.AbstractCoordinatePoint{T})::T where {T}
    ρ::T = 0
    if pt in cdm.G1
        ρ +=  # .... add stuff for G1
    end 
    if pt in cdm.G2
        ρ +=  # .... add stuff for G2
    end
    return ρ
end
```
and add this `ChargeDensity` to the single semiconductor, see an example below.

You can use this structure to overlap `ChargeDensity` that are already implemented in SSD:
```julia
using SolidStateDetectors
using Plots; pyplot()
using IntervalSets
T = Float32

struct CustomChargeDensity{T, N} <: SolidStateDetectors.AbstractChargeDensity{T}
    G1::SolidStateDetectors.AbstractGeometry{T, N}
    G2::SolidStateDetectors.AbstractGeometry{T, N}
    L1::SolidStateDetectors.AbstractChargeDensity{T}
    L2::SolidStateDetectors.AbstractChargeDensity{T}
end

function SolidStateDetectors.get_charge_density(cdm::CustomChargeDensity{T}, pt::SolidStateDetectors.AbstractCoordinatePoint{T})::T where {T}
    ρ::T = 0
    if pt in cdm.G1
        ρ += SolidStateDetectors.get_charge_density(cdm.L1, pt)
    end 
    if pt in cdm.G2
        ρ += SolidStateDetectors.get_charge_density(cdm.L2, pt)
    end
    return ρ
end
```

Find a minimum working example with existing geometries and `ChargeDensity` here:
```julia
using SolidStateDetectors
using IntervalSets
using Plots
T = Float32

struct CustomChargeDensity{T, N} <: SolidStateDetectors.AbstractChargeDensity{T}
    G1::SolidStateDetectors.AbstractGeometry{T, N}
    G2::SolidStateDetectors.AbstractGeometry{T, N}
    L1::SolidStateDetectors.AbstractChargeDensity{T}
    L2::SolidStateDetectors.AbstractChargeDensity{T}
end

#compact version of the function I showed before
function SolidStateDetectors.get_charge_density(cdm::CustomChargeDensity{T}, pt::SolidStateDetectors.AbstractCoordinatePoint{T})::T where {T}
       (pt in cdm.G1) * SolidStateDetectors.get_charge_density(cdm.L1, pt) + 
       (pt in cdm.G2) * SolidStateDetectors.get_charge_density(cdm.L2, pt)
end

G1 = SolidStateDetectors.Tube{T}(0..0.1,0..2π,0..0.04,missing)     #Tube with 0 ≤ z ≤ 0.04
G2 = SolidStateDetectors.Box{T}((-1,1),(-1,1),(0.02,0.08),missing) #Box with 0.02 ≤ z ≤ 0.08
CD1 = SolidStateDetectors.CylindricalChargeDensity{T}((0.0f0, 0.0f0, 1.0f16), (1.0f17, 0.0f0, 1.0f17))
CD2 = SolidStateDetectors.LinearChargeDensity{T}((0.0f0, 0.0f0, 1.0f15), (1.0f17, 0.0f0, 0.0f0))
ccdm = CustomChargeDensity(G1,G2,CD1,CD2)

simulation = Simulation{T}(SSD_examples[:InvertedCoax]) #adjusted phi in the grid to go from 0 to 360 to avoid 2D calculation
simulation.detector.semiconductors[1].charge_density_model = ccdm #apply CustomChargeDensity to the semiconductor
calculate_electric_potential!(simulation, max_refinements = 2)

plot(
    plot(simulation.ρ, φ = 0),
    plot(simulation.ρ, z = 0.01),
    plot(simulation.ρ, z = 0.03),
    plot(simulation.ρ, z = 0.05),
    size = (1200,1200)
)
```
The resulting output is:

output

**Pull request merged**
