### PR TITLE
Tweaks to the logo

### PR DESCRIPTION
**Pull request by schustermartin**
Tweaks to the Logo:
- Added white margin around the "D" part of the logo to establish consistency.
- Added keyword to toggle transparent background.
- Pushed the "etectors" text a tad to the right to improve readability.
- For the .gifs, the first frame (frame 0) now shows the last frame. (Useful for export to .pdf)
- Updated Logos

### CODE REVIEW

**Comment by fhagemann** [comment]
I am not a fan of putting the white margin around the "D".

**Comment by lmh91** [comment]
@schustermartin Can you please provide a comparison picture? Before vs after

**Comment by schustermartin** [comment]
**Current Logo**
logo_current
**New Version**
logo_new
**Respecting Felix' Comment**
logo_new_v2

**Comment by fhagemann** [comment]
I would prefer smaller spacing between "D" and "etectors", something like

Felix

**Comment by lmh91** [comment]
I wanted to suggest the same

**Comment by schustermartin** [comment]
I'll bow to the majority here, but in my opinion Felix last suggestion looks too "pressed" with the grey line. Also the white margin around the "D" would add consistency, even though I have to agree that it thins the grey line too much then.

**Comment by schustermartin** [comment]
**To complete the set**
new_logo_v3

**Comment by lmh91** [comment]
So we have 5 pictures here. Seems to be between 4 and 5. 
I don't have a strong opinion on that, so please, @schustermartin @fhagemann, discuss and
make a commit changing to 4 or 5.

**Comment by fhagemann** [comment]
I am voting for 4.

**Comment by oschulz** [comment]
Nice!

**Pull request merged**
